#!/usr/bin/env sh

# openssl passwd -6 <password>

if [ $# -ne 2 ]; then
    echo 'wrong arguments number'
    echo 'usage: ./encode_configuration <password> <profile name to save in profiles directory>'
    exit -1
fi

CUR_DIR=$(dirname $(readlink -f "$0"))
PROFILES_DIR="$CUR_DIR/profiles"

HASH=$(printf "$1" | shasum -a 512 - | awk '{ print $1 }')
echo $HASH
HASH=${HASH:0:64}
if [ $HASH != 'c0724f8a39315e4b8ea14b5a0ae51ac532ac7255cad4e72b839c3bb055c20f99' ]; then
    echo "wrong password: $1"
    exit -1
fi

openssl aes-256-cbc -a -salt -pbkdf2 -pass "pass:$1" -in "$CUR_DIR/plain_configuration" -out "$PROFILES_DIR/$2"
