#!/usr/bin/env sh

sudo systemctl enable --now dnsmasq.service
sleep 2

! systemctl is-enabled NetworkManager.service > /dev/null && sudo systemctl enable --now NetworkManager.service
systemctl is-enabled NetworkManager-wait-online.service > /dev/null && sudo systemctl disable --now NetworkManager-wait-online.service

. ./env_cfg

[ -z "$CFG_NETWORKMANAGER_SSID" ] && exit

while : ; do
    nmcli device wifi connect "$CFG_NETWORKMANAGER_SSID" password "$CFG_NETWORKMANAGER_PASSWORD"
    [ $? -eq 0 ] && break
    sleep 1
done
