#!/usr/bin/env sh

type pacoloco >/dev/null 2>&1 && return

yay -Sy pacoloco --noconfirm --needed

printf 'Server = http://localhost:9129/repo/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist

sudo systemctl enable --now pacoloco.service
