#!/usr/bin/env sh

source ./env

cat ./lists/LST_BASE ./lists/"LST_$CFG_DESKTOP_ENVIRONMENT" | sudo pacman --needed --noconfirm -S -
sudo systemctl enable ${CFG_DESKTOP_MANAGER}.service

sudo timedatectl set-ntp true

. ./network_manager
sudo systemctl enable --now fstrim.timer bluetooth.service dnsmasq.service

. ./yay


[ -n "$CFG_PACKAGES" ] && yay --sudoloop --needed --noconfirm -S $CFG_PACKAGES
[ -n "$CFG_SYSTEMD" ] && sudo systemctl enable $CFG_SYSTEMD
[ -n "$CFG_GROUPS" ] && sudo usermod -a -G ${CFG_GROUPS// /,} $CFG_USERNAME

MAN_KDBX="$HOME/repo/man.kdbx"
SANCTUM_SANCTORUM="$HOME/.sanctum.sanctorum"
. ./sanctum.sanctorum

