#!/usr/bin/env sh

source ./env

# dots
if [ ! -d "$(chezmoi source-path)" ]; then
    git clone https://github.com/devrtc0/dots.git "$(chezmoi source-path)"
    chmod 0700 $(chezmoi source-path)
    ### uncomment the next line if credentials are stored in dot files
    # sh -c "cd $(chezmoi source-path); git crypt unlock $HOME/.dots.secret"

    sh -c 'cd $(chezmoi source-path); git remote set-url origin git@github.com:devrtc0/dots.git'
    branch=$(printf "$CFG_DESKTOP_ENVIRONMENT" | tr '[:upper:]' '[:lower:]')
    sh -c "cd $(chezmoi source-path); git switch $branch;" && chezmoi apply
fi

. ./settings/"$CFG_DESKTOP_ENVIRONMENT"
