#!/usr/bin/env sh

if [ $# -ne 2 ]; then
    echo 'wrong arguments number'
    echo 'usage: ./zz1 <password> <profile name from profiles directory>'
    exit 1
fi

PASSWD=$1
PROFILE=$2

CUR_DIR=$(dirname "$0")
PROFILES_DIR="$CUR_DIR/profiles"

HASH=$(printf '%s' "$PASSWD" | shasum -a 512 - | awk '{ print $1 }')
HASH=${HASH:0:64}
if [ "$HASH" != 'c0724f8a39315e4b8ea14b5a0ae51ac532ac7255cad4e72b839c3bb055c20f99' ]; then
    echo "wrong password: $PASSWD"
    exit 1
fi

[ ! -f "$PROFILES_DIR/$PROFILE" ] && echo "no profile '$PROFILES_DIR/$PROFILE' exists" && exit 1



type reflector >/dev/null 2>&1 && systemctl stop reflector.service
timedatectl set-ntp true

pacman --noconfirm --needed -Sy

. ./env_cfg

. ./partition

[ -z "$CFG_PACMAN_MIRRORLIST" ] && CFG_PACMAN_MIRRORLIST='Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch
Server = https://mirror.truenetwork.ru/archlinux/$repo/os/$arch
'
echo "$CFG_PACMAN_MIRRORLIST" > /etc/pacman.d/mirrorlist
cp -f ./configurations/common/etc/pacman.conf /etc/pacman.conf

yes | pacstrap /mnt base iptables-nft
genfstab -U /mnt >> /mnt/etc/fstab
sed -i 's/relatime/noatime/' /mnt/etc/fstab

CFG_ROOT_DEVICE=$(lsblk -p -n -o NAME -x NAME "$CFG_DEVICE" | tail -1)
set -a
CFG_ROOT_DEVICE_UUID=$(blkid -s UUID -o value "$CFG_ROOT_DEVICE")
set +a

ENV_SUBST=$(printf '${%s} ' $(env | cut -d'=' -f1 | grep '^CFG_'))

# ----------------------------------
arch-chroot /mnt pacman --needed --noconfirm -Sy

cat ./lists/LST_INIT | envsubst "$ENV_SUBST" | arch-chroot /mnt pacman --needed --noconfirm -S -

# ----------------------------------

find configurations/common/ -type f -print | xargs dirname | sort | uniq | sed 's|^configurations/common|/mnt|' | xargs mkdir -p
for conf in $(find configurations/common/ -type f); do
    cat $conf | envsubst "$ENV_SUBST" > "/mnt${conf#configurations/common}"
done

if [ -d "./configurations/$PROFILE" ]; then
    find "configurations/${PROFILE}/" -type f -print | xargs dirname | sort | uniq | sed "s|^configurations/$PROFILE|/mnt|" | xargs mkdir -p
    for conf in $(find "configurations/${PROFILE}/" -type f); do
        cat "$conf" | envsubst "$ENV_SUBST" > "/mnt${conf#configurations/$PROFILE}"
    done
fi

arch-chroot /mnt /bin/bash <<EOF

date -u | tee -a /usr/lib/arch.meta

locale-gen
ln -s /usr/share/zoneinfo/Europe/Samara /etc/localtime
hwclock --systohc --utc
printf 'root:$CFG_ROOT_PASSWORD' | chpasswd -e
useradd -m -g users -G audio,video,power,storage,wheel,scanner,network -p '$CFG_USER_PASSWORD' -s /bin/fish $CFG_USERNAME
bootctl install
mkinitcpio -P

systemctl enable sshd.service

EOF

arch-chroot /mnt sudo -u "$CFG_USERNAME" sh <<EOF

mkdir -p /home/${CFG_USERNAME}/.ssh
printf 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKPBlmW9r5Y8Zj8cTxECLO9HEY+USByhVDxdPxq++oy2 id_ed25519
' > /home/${CFG_USERNAME}/.ssh/authorized_keys

mkdir -p /home/${CFG_USERNAME}/.config/dnsmasq.d

mkdir -p /home/${CFG_USERNAME}/repo
git clone https://github.com/manjlhh/arch.git /home/${CFG_USERNAME}/repo/arch
cd /home/${CFG_USERNAME}/repo/arch
./decode_configuration $PASSWD $PROFILE

EOF
