#!/usr/bin/env sh

type reflector >/dev/null 2>&1 && systemctl stop reflector.service
timedatectl set-ntp true

pacman --noconfirm --needed -Sy

source ./env_cfg

. ./partition

[ -z "$CFG_PACMAN_MIRRORLIST" ] && CFG_PACMAN_MIRRORLIST='Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch
Server = https://mirror.truenetwork.ru/archlinux/$repo/os/$arch
'
echo "$CFG_PACMAN_MIRRORLIST" > /etc/pacman.d/mirrorlist
cp -f ./configurations/etc/pacman.conf /etc/pacman.conf

yes | pacstrap /mnt base
genfstab -U /mnt >> /mnt/etc/fstab
sed -i 's/relatime/noatime/' /mnt/etc/fstab

CFG_ROOT_DEVICE=$(lsblk -p -n -o NAME -x NAME $CFG_DEVICE | tail -1)
set -a
CFG_ROOT_DEVICE_UUID=$(blkid -s UUID -o value "$CFG_ROOT_DEVICE")
set +a

ENV_SUBST=$(printf '${%s} ' $(env | cut -d'=' -f1 | grep '^CFG_'))

# ----------------------------------
arch-chroot /mnt pacman --needed --noconfirm -Sy

cat ./lists/LST_INIT | envsubst "$ENV_SUBST" | arch-chroot /mnt pacman --needed --noconfirm -S -

# ----------------------------------

find configurations/ -type f -print | xargs dirname | sort | uniq | sed 's/^configurations/\/mnt/' | xargs mkdir -p
for conf in $(find configurations/ -type f); do
    cat $conf | envsubst "$ENV_SUBST" > "/mnt${conf#configurations}"
done

arch-chroot /mnt /bin/bash <<EOF

locale-gen
ln -s /usr/share/zoneinfo/Europe/Samara /etc/localtime
hwclock --systohc --utc
printf 'root:$CFG_ROOT_PASSWORD' | chpasswd -e
useradd -m -g users -G audio,video,power,storage,wheel,scanner,network -p '$CFG_USER_PASSWORD' -s /bin/fish $CFG_USERNAME
bootctl install
mkinitcpio -P

EOF

PASSWD=$1
PROFILE=$2
arch-chroot /mnt sudo -u ${CFG_USERNAME} sh <<EOF

mkdir -p /home/${CFG_USERNAME}/repo
git clone https://github.com/devrtc0/arch.git /home/${CFG_USERNAME}/repo/arch
cd /home/${CFG_USERNAME}/repo/arch
./decode_configuration $PASSWD $PROFILE

EOF
