#!/usr/bin/env sh

sudo timedatectl set-ntp true
sudo systemctl enable --now doh-client dnsmasq

sleep 2
sh ./network_manager
sleep 3

. ./env_cfg

cat ./lists/LST_BASE | sudo pacman --needed --noconfirm -S -

sh ./apps/yay

sudo systemctl enable fstrim.timer bluetooth.service
systemctl --user enable syncthing

[ -n "$CFG_PACKAGES" ] && yay --sudoloop --needed --noconfirm -S $CFG_PACKAGES
[ -n "$CFG_SYSTEMD" ] && sudo systemctl enable $CFG_SYSTEMD
[ -n "$CFG_GROUPS" ] && sudo usermod -a -G ${CFG_GROUPS// /,} "$CFG_USERNAME"

sh ./sanctum.sanctorum
