#!/usr/bin/env sh

sudo timedatectl set-ntp true

sh ./network_manager

sudo systemctl enable --now dnsmasq doh-client

sleep 3

. ./env_cfg

cat ./lists/LST_BASE | sudo pacman --needed --noconfirm -S -

sh ./apps/yay

sudo systemctl enable fstrim.timer bluetooth.service

[ -n "$CFG_PACKAGES" ] && yay --sudoloop --needed --noconfirm -S $CFG_PACKAGES
[ -n "$CFG_SYSTEMD" ] && sudo systemctl enable $CFG_SYSTEMD
[ -n "$CFG_GROUPS" ] && sudo usermod -a -G ${CFG_GROUPS// /,} "$CFG_USERNAME"

sh ./sanctum.sanctorum
