#!/usr/bin/env sh

. ./env_cfg

./apps/yay
./apps/go
./apps/rust
./apps/dotter
[ "$CFG_DE" = "PLASMA" ] && ./apps/systemd-ssh-agent

case "$CFG_DE" in
"PLASMA")
    de="plasma"
    ;;
"GNOME")
    de="gnome"
    ;;

*)
    de="default"
    ;;
esac

sh -c "cd $HOME/repo/dots; dotter deploy -f -l .dotter/$de.toml"

sh -c "cd $HOME/repo/arch/settings && ./$de.sh"
