#!/usr/bin/env sh

. ./env_cfg

if [ -n "$CFG_DE" ]; then
    cat ./lists/LST_X ./lists/LST_$CFG_DE | sudo pacman --needed --noconfirm -S -
fi

if [ -n "$CFG_DESKTOP_MANAGER" ]; then
    sudo systemctl enable "$CFG_DESKTOP_MANAGER.service"
fi
