#!/usr/bin/env sh

gsettings set org.gnome.system.locale region 'en_GB.UTF-8'

gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'

gsettings set org.gnome.desktop.screensaver lock-enabled false

gsettings set org.gnome.desktop.interface monospace-font-name 'Hack 11'
gsettings set org.gnome.desktop.interface show-battery-percentage true

gsettings set org.gnome.desktop.media-handling autorun-never true
gsettings set org.gnome.desktop.media-handling automount false

gsettings set org.gnome.desktop.input-sources per-window true
gsettings set org.gnome.desktop.input-sources sources [('xkb', 'us'), ('xkb', 'ru')]
gsettings set org.gnome.desktop.input-sources xkb-options ['grp:caps_toggle']
gsettings set org.gnome.desktop.wm.keybindings switch-input-source []
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward []
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 25
gsettings set org.gnome.desktop.peripherals.keyboard delay 250
gsettings set org.gnome.desktop.peripherals.keyboard numlock-state true

gsettings set org.gnome.desktop.privacy report-technical-problems false
gsettings set org.gnome.desktop.privacy send-software-usage-stats false

# Terminal F10
gsettings set org.gnome.Terminal.Legacy.Settings menu-accelerator-enabled false

# **************************************************************************************
# **************************************************************************************
# **************************************************************************************

sh -c "cd $HOME/repo/settings/dots; dotter deploy -f -l .dotter/gnome.toml"
