#!/usr/bin/env sh

pacman -Qqi jdk11-openjdk >/dev/null 2>&1 || PKGS="$PKGS jdk11-openjdk"
pacman -Qqi openjdk11-doc >/dev/null 2>&1 || PKGS="$PKGS openjdk11-doc"
pacman -Qqi openjdk11-src >/dev/null 2>&1 || PKGS="$PKGS openjdk11-src"

[ ! -z "$PKGS" ] && sudo pacman --needed --noconfirm -S $PKGS

echo "done"
