#!/usr/bin/env sh

pacman -Qqi jdk17-openjdk >/dev/null 2>&1 || PKGS="$PKGS jdk17-openjdk"
pacman -Qqi openjdk17-doc >/dev/null 2>&1 || PKGS="$PKGS openjdk17-doc"
pacman -Qqi openjdk17-src >/dev/null 2>&1 || PKGS="$PKGS openjdk17-src"

[ ! -z "$PKGS" ] && sudo pacman --needed --noconfirm -S $PKGS

echo "done"
