#!/usr/bin/env sh

pacman -Qqi jdk-openjdk >/dev/null 2>&1 || PKGS="$PKGS jdk-openjdk"
pacman -Qqi openjdk-doc >/dev/null 2>&1 || PKGS="$PKGS openjdk-doc"
pacman -Qqi openjdk-src >/dev/null 2>&1 || PKGS="$PKGS openjdk-src"

[ ! -z "$PKGS" ] && sudo pacman --needed --noconfirm -S $PKGS
