#!/usr/bin/env sh

pacman -Qeq jdk-openjdk >/dev/null 2>&1 || sudo pacman --needed --noconfirm -S jdk-openjdk
pacman -Qeq openjdk-doc >/dev/null 2>&1 || sudo pacman --needed --noconfirm -S openjdk-doc
pacman -Qeq openjdk-src >/dev/null 2>&1 || sudo pacman --needed --noconfirm -S openjdk-src
