#!/usr/bin/env sh

for name in "podman" "podman-compose" "cockpit-podman" "aardvark-dns"
do
	pacman -Qi "$name" >/dev/null 2>&1 || APPS="$APPS $name"
done

if [ -n "$APPS" ]; then
	sudo pacman --needed --noconfirm -S $APPS
fi

printf '[[registry]]
location = "docker.io"
' | sudo tee /etc/containers/registries.conf.d/01-registries.conf

printf 'unqualified-search-registries = ["docker.io"]
' | sudo tee /etc/containers/registries.conf.d/00-unqualified-search-registries.conf
