#!/usr/bin/env sh

pacman -Qeq rustup >/dev/null 2>&1 || sudo pacman --needed --noconfirm -S rustup
pacman -Qeq rust-analyzer >/dev/null 2>&1 || sudo pacman --needed --noconfirm -S rust-analyzer

rustup default stable
